# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skintone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_tone', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='undertone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_tone', models.CharField(max_length=250)),
            ],
        ),
    ]
