# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skincolor_accessor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skintone',
            name='example_photo',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
